Feeling statistic fix
Kestava-keikkatyo/innoFrontend pull request #114
Opened 2023-10-09 04:17 UTC by hannaihe

2023-10-09 18:04 UTC, seblundin requested changes
Yritin itsekin löytää tuolle any tyypitykselle parempaa vaihtoehtoa mutta pitäis melkein tyypittää uusiksi koko paskasovellus :DD any käy siis minunki puolesta ihan hyvin, mutta jos paremman vaihtoehdon pystyy laittamaan, niin mielellään joku järkevä tyyppi.

Laitoin muutaman korjausehdotuksen tuohon AgencyStatisticsSummaryyn. Lähinnä console logeja pois ja yksi pieni uudelleenjärjestely + ehdot useEffectiin

2023-10-09 18:04 UTC, seblundin commented on src/pages/MoodStatistics/AgencyStatisticsSummary.tsx
> +  if (role == roles.Business) {
```suggestion
  if (role === roles.Business) {
```

2023-10-09 18:04 UTC, seblundin commented on src/pages/MoodStatistics/AgencyStatisticsSummary.tsx
> +  if (role == roles.Agency) {
```suggestion
  if (role === roles.Agency) {
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality

2023-10-09 18:04 UTC, seblundin commented on src/pages/MoodStatistics/AgencyStatisticsSummary.tsx
> +    dispatch(fetchEmploymentContractsAsWorkerOrBusiness())
```suggestion
    role === roles.Agency && dispatch(fetchContractsAsAgency())
    role === roles.Business && dispatch(fetchEmploymentContractsAsWorkerOrBusiness())
```
Tähän vois laittaa jonku tämäntyylisen ehdon, että haetaan oikeantyyppisellä käyttäjällä oikeasta rajapinnasta.

2023-10-09 18:04 UTC, seblundin commented on src/pages/MoodStatistics/AgencyStatisticsSummary.tsx
> +  console.log(allFeelings)
```suggestion
```

2023-10-09 18:04 UTC, seblundin commented on src/pages/MoodStatistics/AgencyStatisticsSummary.tsx
> +        console.log(allFeelings[i].feeling + ' antoi ' + allFeelings[i].worker)
```suggestion
```

2023-10-09 18:04 UTC, seblundin commented on src/pages/MoodStatistics/AgencyStatisticsSummary.tsx
> +  console.log(feelingsList)
```suggestion
```

2023-10-09 18:04 UTC, seblundin commented on src/pages/MoodStatistics/AgencyStatisticsSummary.tsx
> +    console.log(contractsBusiness)
```suggestion
```

2023-10-09 18:04 UTC, seblundin commented on src/pages/MoodStatistics/AgencyStatisticsSummary.tsx
>    }
```suggestion
```
Siirretään suoraan muuttujan määrittelyyn

2023-10-09 18:04 UTC, seblundin commented on src/pages/MoodStatistics/AgencyStatisticsSummary.tsx
> +  const { feelings } = useSelector((state: IRootState) => state.feeling)
```suggestion
```
siirretään ylemmäs

2023-10-09 18:04 UTC, seblundin commented on src/pages/MoodStatistics/AgencyStatisticsSummary.tsx
> +  const allFeelings: Feeling[] = [] //All feelings
```suggestion
  const { feelings } = useSelector((state: IRootState) => state.feeling)
  const allFeelings: Feeling[] = [...feelings.data] //All feelings
```
Tänne suoraan allFeelings määrittely

2023-10-10 05:00 UTC, hannaihe commented on src/pages/MoodStatistics/AgencyStatisticsSummary.tsx
> +  const allFeelings: Feeling[] = [] //All feelings
Ei toimi näin, koko etusivu menee särki

2023-10-10 05:18 UTC, seblundin commented on src/pages/MoodStatistics/AgencyStatisticsSummary.tsx
> +  const allFeelings: Feeling[] = [] //All feelings
Joo sori mulla kävi burgér

2023-10-10 05:19 UTC, seblundin approved these changes

2023-10-10 05:32 UTC, merged