Top bar refactoring
Kestava-keikkatyo/innoFrontend pull request #122
Opened 2023-10-22 17:06 UTC by seblundin

Got annoyed of the spaghetti mountain that is TopAppBar. Cleaned it up a lot. Still room for improvements. Fixed many other things in the process.

![https://media.tenor.com/jkRrt2SrlMkAAAAC/pepe-nuke.gif](https://media.tenor.com/jkRrt2SrlMkAAAAC/pepe-nuke.gif)

2023-10-22 17:35 UTC, Rutto404 approved these changes

2023-10-23 06:03 UTC, hannaihe requested changes
Palautetaan valikkojen fontti samaksi kuin ennen ja tehdään näkymästä leveä

2023-10-24 18:54 UTC, seblundin commented
> Palautetaan valikkojen fontti samaksi kuin ennen ja tehdään näkymästä leveä

Nuketin vähän lisää ja tein ulkoasusta mahdollisimman paljon entistä vastaavan. Katselin samalla, että näyttäisi mahdollisimman paljon designin mukaiselta. @hannaihe

2023-10-25 04:24 UTC, hannaihe approved these changes
Nättiä!!

2023-10-25 04:55 UTC, merged